[build]
builder = "nixpacks"

[deploy]
startCommand = "node --experimental-require-module server.js"
healthcheckPath = "/health"
healthcheckTimeout = 45
restartPolicyType = "always"

[[volumes]]
mountPath = "/app/sessions"
